from PyQt6.QtWidgets import QFrame
from PyQt6.QtCore import Qt, QBasicTimer, pyqtSignal, QPointF, QPoint
from PyQt6.QtGui import QPainter, QBrush, QColor
from game_logic import GameLogic
from piece import Piece


class Board(QFrame):  # base the board on a QFrame widget
    updateTimerSignal = pyqtSignal(int)  # signal sent when timer is updated
    clickLocationSignal = pyqtSignal(str)  # signal sent when there is a new click location

    # TODO set the board width and height to be square
    boardWidth = 8  # board is 0 squares wide # TODO this needs updating
    boardHeight = 8  #
    timerSpeed = 1000  # the timer updates every 1 millisecond
    counter = 10  # the number the counter will count down from

    def __init__(self, parent):
        super().__init__(parent)
        self.initBoard()

    def initBoard(self):
        '''initiates board'''
        self.timer = QBasicTimer()  # create a timer for the game
        self.isStarted = False  # game is not currently started
        self.start()  # start the game which will start the timer
        self.points_coordinates_undo = []  # Stack that contains all the intersections used by players. Used for undo
        self.points_coordinates_redo = []  # Stack that contains all the points that were popped in the undo method
        self.points_status_undo = []
        self.points_status_redo = []

        self.boardArray = [[Piece(0, j, i) for i in range(Board.boardHeight - 1)] for j in
                           range(Board.boardWidth - 1)]
        # self.printBoardArray()  # TODO - uncomment this method after creating the array above

        # Create an instance of the logic object here to enforce the rules of this game
        self.logic = GameLogic()

        # Save the x & y positioned generated by the mousePressEvent, so it can be converted to an intersection position
        # These x & y positions will be passed to the Piece class constructor so a new Piece can be placed
        self.x_position = 0
        self.y_position = 0

    def printBoardArray(self):
        '''prints the boardArray in an attractive way'''
        print("boardArray:")
        print('\n'.join(['\t'.join([str(cell) for cell in row]) for row in self.boardArray]))

    def getCol(self):
        # Get widget width and divide it by the amount of squares on the board
        width = self.width() / Board.boardWidth
        col = int(round(self.x_position / width)) - 1  # Add the -1 to account for the whitespace
        return col

    def getRow(self):
        # Get the widget height and divide it by the amount of squares on the board
        height = self.height() / Board.boardHeight
        row = int(round(self.y_position / height)) - 1  # Add the -1 to account for the whitespace
        return row

    def getColCoordinatesForPaint(self, col):
        # print("Y position: " + str(self.y_position))
        # print("Board Size: " + str(self.width()))
        # print("Board Square Width: " + str(self.width() / Board.boardWidth))
        return (col + 1) * self.width() / Board.boardWidth

    def getRowCoordinatesForPaint(self, row):
        return (row + 1) * self.height() / Board.boardHeight

    def squareWidth(self):
        '''returns the width of one square in the board'''
        return self.contentsRect().width() / self.boardWidth

    def squareHeight(self):
        '''returns the height of one square of the board'''
        return self.contentsRect().height() / self.boardHeight

    def start(self):
        '''starts game'''
        self.isStarted = False  # set the boolean which determines if the game has started to TRUE
        self.resetGame()  # reset the game
        self.timer.start(self.timerSpeed, self)  # start the timer with the correct speed
        # print("start () - timer is started")  # Commenting out to test other methods

    def timerEvent(self, event):
        '''this event is automatically called when the timer is updated. based on the timerSpeed variable '''
        # TODO adapt this code to handle your timers
        if event.timerId() == self.timer.timerId():  # if the timer that has 'ticked' is the one in this class
            if Board.counter == 0:
                print("Game over")
            self.counter -= 1

            # print('timerEvent()', self.counter)
            self.updateTimerSignal.emit(self.counter)
        else:
            super(Board, self).timerEvent(event)  # if we do not handle an event we should pass it to the super
            # class for handling

    def paintEvent(self, event):
        '''paints the board and the pieces of the game'''
        painter = QPainter(self)
        self.drawBoardSquares(painter)
        self.drawPieces(painter)

    def mousePressEvent(self, event):
        '''this event is automatically called when the mouse is pressed'''
        clickLoc = "click location [" + str(event.position().x()) + "," + str(
            event.position().y()) + "]"  # the location where a mouse click was registered
        # print("mousePressEvent() - " + clickLoc)
        # Set the x-position and the y-position
        self.x_position = int(event.position().x())
        self.y_position = int(event.position().y())

        # TODO you could call some game logic here
        self.clickLocationSignal.emit(clickLoc)

        # Check if the mouse click was within the range of the board
        if self.checkWithinRange():
            # Check if a space is occupied
            if self.boardArray[self.getRow()][self.getCol()].getPiece() == 0:
                # Check that both players have not passed their turns, their booleans will both be true if they have
                if self.logic.checkIfBothPlayersPassed():
                    print("Both players have passed")
                else:
                    # Try to make the move
                    if self.tryMove(self.getRow(), self.getCol()):  # If the move returns ture the it passed both the
                        # Suicide test and the KO test
                        self.logic.increaseTurn()
                        self.logic.addToGameState(self.boardArray)
                    else:
                        # If the move is false then revert the board to the previous state
                        self.logic.rewriteBoard(self.boardArray)
                        # Maybe put a pop up here to say invalid move?

    def checkWithinRange(self):
        width = self.width() / Board.boardWidth
        height = self.height() / Board.boardHeight
        if (width / 2) < self.x_position < ((width * 8) + (width / 2)) and \
                ((height / 2) < self.y_position < (height * 8 + (height / 2))):
            return True

    def resetGame(self):
        '''clears pieces from the board'''
        # TODO write code to reset game

    def tryMove(self, newX, newY):
        """tries to move a piece"""
        # Check whose turn it is
        turn = self.logic.checkTurn()

        # Set the Player's Passed boolean to False as they are currently trying to make a move
        self.logic.setPlayerPassed(turn, False)
        # Get the current state of the board to have a reference if we have to reset it due to not passing the KO rule
        self.logic.setCurrentState(self.boardArray)

        # Place the stone
        self.boardArray[newX][newY].setStatus(turn)

        # Check the suicide rule
        if self.logic.checkForSuicide(newX, newY, self.boardArray, turn):  # If it's suicide then do this
            # Check if a piece or pieces will be taken
            self.checkAllDirectionsForCapture(newX, newY, turn)
        else:  # If it isn't suicide then do this
            # Place the stone
            # Check to see if pieces are taken
            self.checkAllDirectionsForCapture(newX, newY, turn)

        # Now check to see if the new state of the board is equal to the previous (KO rule)
        validMove = self.logic.checkKORule(self.boardArray)

        self.update()
        return validMove

    def drawBoardSquares(self, painter):
        '''draw all the square on the board'''
        # Setting the default color of the brush
        brush = QBrush(Qt.BrushStyle.SolidPattern)
        brush.setColor(Qt.GlobalColor.transparent)
        painter.setBrush(brush)
        # Declaring and initializing the colors for the board
        color_one = QColor(214, 178, 112)
        color_two = QColor(199, 105, 41)
        for row in range(1, Board.boardHeight - 1):
            for col in range(1, Board.boardWidth - 1):
                painter.save()
                # Setting the value equal the transformation in the column direction
                colTransformation = self.squareWidth() * col
                # Setting the value equal the transformation in the row direction
                rowTransformation = self.squareHeight() * row
                painter.translate(colTransformation, rowTransformation)
                # Changing the colors to create a checkered board
                if row % 2 == 0:
                    if col % 2 != 0:
                        brush.setColor(color_one)
                    elif col % 2 == 0:
                        brush.setColor(color_two)
                else:
                    if col % 2 != 0:
                        brush.setColor(color_two)
                    elif col % 2 == 0:
                        brush.setColor(color_one)
                # Setting X and Y coordinates and painting a square base on the calculated
                # width and height of squareWidth and squareHeight methods with the created brush
                painter.fillRect(col, row, int(self.squareWidth()), int(self.squareHeight()), brush)
                painter.restore()

    def drawPieces(self, painter):
        '''draw the prices on the board'''
        colour = Qt.GlobalColor.transparent  # empty square could be modeled with transparent pieces
        for row in range(0, len(self.boardArray)):
            for col in range(0, len(self.boardArray[0])):
                painter.save()
                # TODO draw some the pieces as ellipses
                # resize the piece by 2
                painter.translate(((self.squareWidth()) * row) + self.squareWidth() * 0.75,
                                  (self.squareHeight()) * col + self.squareHeight() * 0.75)

                # Transparent for when there is no piece on the board
                if self.boardArray[col][row].getPiece() == 0:
                    colour = QColor(Qt.GlobalColor.transparent)
                # White color for when it is white's turn
                elif self.boardArray[col][row].getPiece() == 1:
                    colour = QColor(Qt.GlobalColor.white)
                # Black color for when there black's turn
                elif self.boardArray[col][row].getPiece() == 2:
                    colour = QColor(Qt.GlobalColor.black)

                painter.setPen(colour)
                painter.setBrush(colour)
                radiusW = self.squareWidth() / 4
                radiusH = self.squareHeight() / 4

                center = QPointF(radiusW, radiusH)
                painter.drawEllipse(center, radiusW, radiusH)
                painter.restore()

    def undo(self):
        print("Undo")
        # Checks first if the stack is empty. If not empty, it starts popping values
        if self.points_coordinates_undo.__len__() != 0 and self.points_status_undo.__len__() != 0:
            point_status = self.points_status_undo.pop()
            # Pop and store the value inside the variable
            point_value = self.points_coordinates_undo.pop()
            print("Status = " + str(point_status))
            # Storing removed point inside the redo stack
            self.points_coordinates_redo.append(point_value)
            # Get the row and col indexes
            row_point = point_value.x()
            col_point = point_value.y()
            # Set the specific index to 0 (transparent)
            self.boardArray[row_point][col_point].setStatus(0)
            self.points_status_redo.append(point_status)
            # Calling update method to re draw board and pieces
            self.update()

    def redo(self):
        if self.points_coordinates_redo.__len__() != 0 and self.points_status_redo.__len__() != 0:
            point_status = self.points_status_redo.pop()
            # Pop and store the value inside the variable
            point_value = self.points_coordinates_redo.pop()
            # Storing removed point inside the undo stack
            self.points_coordinates_undo.append(point_value)
            # Get the row and col indexes
            row_point = point_value.x()
            col_point = point_value.y()
            # Set the specific index to 0 (transparent)
            self.boardArray[row_point][col_point].setStatus(point_status)
            # Calling update method to re draw board and pieces
            self.update()

    def checkAllDirectionsForCapture(self, newX, newY, turn):
        # Check if the top group will be captured
        top = self.logic.checkForGroup(newX, newY, self.boardArray, turn, "top")
        if top:
            self.logic.capture(self.boardArray)

        self.logic.emptyList()

        # Check if the bottom group will be captured
        bottom = self.logic.checkForGroup(newX, newY, self.boardArray, turn, "bottom")
        if bottom:
            self.logic.capture(self.boardArray)

        self.logic.emptyList()

        # Check if the left group will be captured
        left = self.logic.checkForGroup(newX, newY, self.boardArray, turn, "left")
        if left:
            self.logic.capture(self.boardArray)
        self.logic.emptyList()

        # Check if the right group will be captured
        right = self.logic.checkForGroup(newX, newY, self.boardArray, turn, "right")
        if right:
            self.logic.capture(self.boardArray)
        self.logic.emptyList()

        # If it's a valid move then update the paint (gui) and increase turn counter, and update the GameState
        if top or bottom or left or right:
            return True
        # If it isn't a valid move then maybe a pop up saying 'It's Suicide!'? and return without increasing the
        # Counter? Or re-painting
        else:
            return False
